# SPDX-License-Identifier: Apache-2.0
"""Integration checks using the same pinned analyzers as CI."""

import importlib.util
import json
from pathlib import Path
import subprocess
import tempfile
import unittest
from unittest.mock import patch


SCRIPT = Path(__file__).resolve().parents[1] / "check-complexity.py"
SPEC = importlib.util.spec_from_file_location("complexity", SCRIPT)
complexity = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(complexity)


class ComplexityTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)

    def write(self, name, source):
        path = self.root / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source)
        return path

    def git(self, *args):
        subprocess.run(["git", *args], cwd=self.root, check=True, capture_output=True)

    def test_source_discovery(self):
        self.git("init", "-q")
        self.write(".gitignore", "ignored/\n")
        self.write("tracked.go", "package example\n")
        self.git("add", ".")
        self.write("new file.go", "package example\n")
        self.write("ignored/example.go", "package example\n")
        self.write("vendor/example.go", "package example\n")
        self.write("generated/example.go", "package example\n")
        self.write("binding.go", "// Code generated by abigen. DO NOT EDIT.\npackage example\n")
        patch_path = "packages/go-anchor/ics07_tendermint_patches/instructions.go"
        self.write(patch_path, "// Lives outside the auto-generated packages.\npackage patches\n")
        (self.root / "link.go").symlink_to("tracked.go")
        self.assertEqual(complexity.source_files(self.root, "go"),
                         ["new file.go", patch_path, "tracked.go"])
        (self.root / "tracked.go").unlink()
        self.assertNotIn("tracked.go", complexity.source_files(self.root, "go"))

    def test_go_limit_boundary(self):
        for score in (30, 31):
            with self.subTest(score=score):
                self.write("boundary.go", "package example\nfunc boundary(x bool) {\n"
                           + "if x {}\n" * (score - 1) + "}\n")
                metrics = list(complexity.go_metrics(self.root, ["boundary.go"]))
                self.assertEqual(metrics[0][3], score)
                errors = list(complexity.violations(metrics, {"max": 30}))
                self.assertEqual(bool(errors), score > 30)

    def test_rust_limit_boundary(self):
        for score in (30, 31):
            with self.subTest(score=score):
                self.write("boundary.rs", "fn boundary(x: bool) {\n"
                           + "if x {}\n" * (score - 1) + "}\n")
                metrics = list(complexity.rust_metrics(self.root, ["boundary.rs"]))
                self.assertEqual(metrics[0][3], score)
                errors = list(complexity.violations(metrics, {"max": 30}))
                self.assertEqual(bool(errors), score > 30)

    def test_rust_match_arms_and_multiple_files(self):
        self.write("arms.rs", "fn arms(x: u8) -> u8 { match x { 0 => 1, 1 => 2, 2 => 3, _ => 4 } }")
        self.write("simple.rs", "fn simple() {}")
        metrics = list(complexity.rust_metrics(self.root, ["arms.rs", "simple.rs"]))
        scores = {metric[1]: metric[3] for metric in metrics}
        self.assertGreaterEqual(scores["arms"], 4)
        self.assertEqual(scores["simple"], 1)

    def test_nested_rust_function_is_not_added_to_parent(self):
        self.write("nested.rs", "fn outer() { fn inner(x: bool) { if x {} } }")
        metrics = list(complexity.rust_metrics(self.root, ["nested.rs"]))
        scores = {metric[1]: metric[3] for metric in metrics}
        self.assertEqual(scores, {"outer": 1, "outer::inner": 2})

    def test_go_receiver_identity_and_spaces_in_paths(self):
        self.write("space in path.go", "package example\ntype A struct{}\n"
                   "func (a *A) method(x bool) { if x {} }\n")
        metrics = list(complexity.go_metrics(self.root, ["space in path.go"]))
        self.assertEqual(metrics, [("space in path.go", "(*A).method", 3, 2)])

    def test_exceptions_cap_existing_functions_and_require_cleanup(self):
        config = {"max": 30, "exceptions": {"example.go::legacy": {"max": 48}}}
        for score, fails in ((48, False), (49, True), (47, True), (30, True)):
            with self.subTest(score=score):
                errors = list(complexity.violations([("example.go", "legacy", 1, score)], config))
                self.assertEqual(bool(errors), fails)
        self.assertTrue(list(complexity.violations([], config)))
        self.assertTrue(list(complexity.violations([("other.go", "legacy", 1, 48)], config)))

    def test_analyzer_failure_is_not_a_pass(self):
        failed = subprocess.CalledProcessError(1, "analyzer", stderr="parse error")
        for analyze in (complexity.go_metrics, complexity.rust_metrics):
            with self.subTest(analyzer=analyze.__name__):
                with patch.object(complexity.subprocess, "run", side_effect=failed):
                    with self.assertRaises(subprocess.CalledProcessError):
                        list(analyze(self.root, ["example"]))

    def test_missing_rust_output_is_not_a_pass(self):
        empty = subprocess.CompletedProcess([], 0, stdout="", stderr="")
        with patch.object(complexity.subprocess, "run", return_value=empty):
            with self.assertRaises(ValueError):
                list(complexity.rust_metrics(self.root, ["missing.rs"]))

    def test_solhint_complexity_rule_is_enforced(self):
        solidity = complexity.ROOT / "ibc-solidity"
        for score in (8, 9):
            with self.subTest(score=score):
                path = self.write("Boundary.sol", "// SPDX-License-Identifier: Apache-2.0\n"
                                  "pragma solidity ^0.8.25;\ncontract Boundary {\n"
                                  "function boundary(bool x) external pure {\n"
                                  + "if (x) {}\n" * (score - 1) + "}\n}\n")
                result = subprocess.run(
                    ["bun", "solhint", "--config", str(solidity / ".solhint.json"),
                     "--formatter", "json", "stdin"],
                    cwd=solidity, input=path.read_text(), capture_output=True, text=True,
                )
                # Solhint's JSON formatter emits a flat list of messages plus a
                # trailing conclusion entry, so filter on the rule id directly.
                errors = [message for message in json.loads(result.stdout)
                          if message.get("ruleId") == "code-complexity"]
                self.assertEqual(bool(errors), score > 8)
                if score > 8:
                    self.assertNotEqual(result.returncode, 0)


if __name__ == "__main__":
    unittest.main()
