# SPDX-License-Identifier: Apache-2.0

name: complexity

on:
  push:
    branches: [main]
  pull_request:

permissions: {}

jobs:
  cyclomatic-complexity:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test complexity enforcement
        run: nix develop .#complexity --command just test-complexity
      - name: Check Solidity, Go, and Rust complexity
        run: nix develop .#complexity --command just lint-complexity
